### ISSUE TITLE
gnome的配置

### ISSUE THREAD

**Issue by lclgo** [Geass-LL/Geass-LL.github.io#23]
## 自动隐藏TopBar

`apt install gnome-shell-extension-autohidetopbar`，重启后打开tweaks配置

![Image](https://github.com/user-attachments/assets/eac0adaf-aa56-4c21-8cf0-0d0b6a6175fd)

## 息屏锁屏配置

|配置|命令|
|-|-|
|熄屏时间|gsettings set org.gnome.desktop.session idle-delay 1800|
|熄屏后是否锁定|gsettings set org.gnome.desktop.screensaver lock-enabled true|
|熄屏后到锁定的等待时间|gsettings set org.gnome.desktop.screensaver lock-delay 3600|

上述命令使用普通用户执行即可，`set`替换为`get`查询是否生效。

作为服务器使用时，需要一劳永逸解决休眠断网问题：`systemctl mask sleep.target suspend.target`

## 标题栏宽度修改

gtk框架应用的标题栏太宽，将标题栏的宽度缩减到24个像素。

```css
/* /home/xxx/.config/gtk-3.0/gtk.css */
headerbar {
    min-height: 16px;
    padding-left: 2px; /* same as childrens vertical margins for nicer proportions */
    padding-right: 2px;
    margin: 0px; /* same as headerbar side padding for nicer proportions */
    padding: 0px;
}
```
